### ISSUE TITLE
Issue with F-Droid

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/Metro#1]
@IzzySoft I noticed that latest versions of Retro Music Player are no longer available in your repo. As I understand that the devs have no intention of putting their player on F-Droid, I made a forked version of this player. Now, I've only removed Google Play API and I'm not sure what other non-free library this piece of software use. Would you please take a look. This is probably the best music player available in the market.

**Comment by IzzySoft** [comment]
The latest release is available in my repo – and as soon as a new version is released (and the devs tag it with an APK attached), it should show up in my repo automatically. So I'm not sure what you mean by the latest versions not being available there. The only newer one is marked "pre-release" and thus skipped by my updater, and since then no new *releases* have been published (only tags have been created).

Ah, I see: they still publish on Play, just no longer provide the APK at Github. Have you asked whether they'd pick that up again? [I just did](https://github.com/h4h13/RetroMusicPlayer/issues/59#issuecomment-645602204), let's see what they say.

PS: Not much for me to look here, as you have no APKs either (and not being an Android dev, I cannot relly tell that by just looking at the code). Or did you mean for publication at F-Droid? Then you could just open an RFP and see what the bot says.

**Comment by MuntashirAkon** [comment]
> Have you asked whether they'd pick that up again?

No, the issue was closed. So, I figured that they're not interested.

> Or did you mean for publication at F-Droid?

Yes, I meant F-Droid repo. But since you've asked the devs, I'll wait for a statement. It would be awesome if they did it.

**Comment by IzzySoft** [comment]
If you use a different package name (which you should do for a fork, as otherwise the two collide), I could add your fork to my repo as well – and then help you getting it to F-Droid.org if you wish.

**Comment by MuntashirAkon** [comment]
I've added fastlane as well as a new release.

**Comment by IzzySoft** [comment]
There's a mismatch in the changelogs. Your APK identifies with versionCode 10441, but the changelog is named `441.txt`. The two must match (as you started with versionCode 10441, I'd suggest to use the higher numbers for changelogs, not the other way around, else the users won't be offered future versions as updates).

Further, `full_description.txt` should be expanded a bit, by the features etc. as it's in upstream (see e.g. [here](https://apt.izzysoft.de/fdroid/index/apk/code.name.monkey.retromusic)), or from your Readme.

Then, tag names should match versionName (or the other way around) – which currently is not the case: tag name has "3.5.8", while versionName has "3.5.8_0628". This will break auto-updates (I'd suggest stripping the date part from versionName, and keeping tag names as-is with `v` prefix).

As a side note: nice short name – but try a search engine of your choice to find where it's mentioned :wink:

Added it to my repo, should show up [here](https://apt.izzysoft.de/fdroid/index/apk/io.github.muntashirakon.Music) in about 5 hours. Thanks!

**Comment by MuntashirAkon** [comment]
Thanks for informing me. I didn't notice the versioning style earlier. I'll update them accordingly.

> As a side note: nice short name – but try a search engine of your choice to find where it's mentioned 😉

Those who'll be looking for it will definitely find it.

**Comment by IzzySoft** [comment]
> Those who'll be looking for it will definitely find it.

The app itself, certainly. But looking for reviews, maybe video presentations etc will be hard, as search engines would simply drop the stand-alone "m" from your search query. Up to you of course, but you should be aware of that. Too generic terms make it problematic (I always find that when searching for something on "Evolution", which I use as my PIM solution – and that's even a full word).

**Comment by MuntashirAkon** [comment]
Then I guess I need to change the app label. Any suggestions?

**Comment by 5c0tt-b0t** [comment]
As it is **M**, and a fork off **Retro**...
How about **Metro** ???

**Comment by Scrumplex** [comment]
Metro sounds really good imo

**Comment by TheEvilSkeleton** [comment]
i like Metro too

**Comment by TheEvilSkeleton** [comment]
@Scrumplex what a coincidence, good to see you here

**Comment by breitbarth** [comment]
> Metro sounds really good imo
> 
> Btw. this might finally be the one replacing Poweramp for me.

Oh, Poweramp. It's been so long.

**Comment by MuntashirAkon** [comment]
Ok, **Metro** is the new name! Thanks everyone for feedback.

**Comment by MuntashirAkon** [comment]
> Btw. this might finally be the one replacing Poweramp for me.

This is no where near Poweramp in terms of features though. Besides, like many other music players, Retro only relies on Android's media scanner which apparently skips some music files.

**Comment by MuntashirAkon** [comment]
@IzzySoft it seems the latest version isn't up yet.

**Comment by IzzySoft** [comment]
As to the mismatch of versionName and tag names at v3.5.8, the update was not recognized (now that the two match, it should work with future releases). I now pulled it manually, will show up with the next sync this evening – thanks for nudging me!

Note: the changelog in fastlane is again misnamed: `10422.txt` should probably be `10442.txt`, right?

**Comment by MuntashirAkon** [comment]
> Note: the changelog in fastlane is again misnamed: `10422.txt` should probably be `10442.txt`, right?

Oops, I will fix that!

**Comment by IzzySoft** [comment]
Cannot hurt :smiley: I've already fixed it on my end, so it should turn up allright in my repo. Thanks!

**Comment by MuntashirAkon** [comment]
I've just opened an RFP: https://gitlab.com/fdroid/rfp/-/issues/1439

**Comment by IzzySoft** [comment]
Umpf. You started by freeing the predecessor from Google Libs, and now you're bringing other Google dependencies in – that's quite unfortunate. Just had to add the `NonFreeNet` AntiFeature, as my library-scanner alerted me about:

* BillingClientⓃ
* Android In-App Billing v3 LibraryⓃ
* Google PlayⓃ
* Google Play CoreⓃ

having been added. Which ties your app to Google again. Not a good idea. Especially in-app billing v3 – I vaguely remember some other (upcoming?) issue with that, like Google requiring some proprietary dependency or the like, I just cannot find it right now. But definitely not a good idea for F-Droid listing…

**Comment by IzzySoft** [comment]
> Now, I've only removed Google Play API

well, it's back in your `build.gradle`:

```gradle
    implementation 'com.google.android.play:core-ktx:1.8.1'
```

I've just triggered the bot over at your RFP. Guess we'll need a flavor without that (and I'd prefer an APK of that flavor for my repo, too). Sorry for the inconvenience…

**Comment by MuntashirAkon** [comment]
> having been added. Which ties your app to Google again. Not a good idea. Especially in-app billing v3 – I vaguely remember some other (upcoming?) issue with that, like Google requiring some proprietary dependency or the like, I just cannot find it right now. But definitely not a good idea for F-Droid listing…

Oops, I've removed the dependencies but forgot to remove them from build.gradle. I'll fix that ASAP.

**Comment by MuntashirAkon** [comment]
Thanks @IzzySoft for informing me about the incident. I've no intention of introducing any non-free libs nor any trackers (not even ACRA).

**Comment by IzzySoft** [comment]
I still wonder why the bot didn't complain about `com.google.android.play:core-ktx:1.8.1` – so the good thing might be we detected a hole in it and get that fixed…

Thanks for your quick action! Please send me a reminder once the next release is out, so I check again. NonFreeNet is one of the few AntiFeatures I get notified when missing (due to some such library being found) – but not when no longer needed (could be global, e.g. a Youtube app).

**Comment by MuntashirAkon** [comment]
@IzzySoft: I've pushed a new release. Hopefully, you can remove the NonFreeNet tag after this.

**Comment by IzzySoft** [comment]
Confirmed – and done! Thanks, good work!

**Comment by MuntashirAkon** [comment]
@IzzySoft Isn't [Google Play Billing library](https://developer.android.com/reference/com/android/billingclient/api/package-summary) closed source?

**Comment by IzzySoft** [comment]
If it's open source, it at least is not free/libre AFAIK.

**Comment by MuntashirAkon** [comment]
**Metro** is now available on F-Droid! Thanks everyone who helped me on this project.

@IzzySoft I think you can safely remove it from your repo now.

**Comment by IzzySoft** [comment]
Will do – after it had some days to settle (and users had some days to notice). I usually give it 5..7 days for that.
