### ISSUE TITLE
Libre.fm/scrobbling support

### ISSUE THREAD

**Issue by emmatebibyte** [MuntashirAkon/Metro#103]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Support for scrobbling on libre.fm and possibly last.fm

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MuntashirAkon** [comment]
Metro is a fully offline player unlike Retro and no longer offers any Internet features.
