### ISSUE TITLE
Integrate Spotify into Metro

### ISSUE THREAD

**Issue by bitsper2nd** [MuntashirAkon/Metro#11]
Not really an issue. More in the line of a feature request. Would it be possible to integrate [Spotify](https://github.com/Valou3433/blade-player/tree/master/app/libs/android-auth-1.0) into Metro like this other music player called [Blade](https://github.com/Valou3433/blade-player) does? I really don't know about android dev, so this is out of my area of expertise.

**Comment by MuntashirAkon** [comment]
Thanks, I myself often use Spotify. I will take a look.

**Comment by bitsper2nd** [comment]
No problem. If you need any help testing, I'm available. I can also some graphic design.
