### ISSUE TITLE
Discord Rich Presence?

### ISSUE THREAD

**Issue by okwolf24** [MuntashirAkon/Metro#110]
**Is your feature request related to a problem? Please describe.**
It isn't related to a problem, but a rather question referring to a possible feature.

**Describe the solution you'd like**
I wanted to ask about whether or not it would be possible to add a feature for music that's being played to be displayed on Discord as a Rich Presence; similar to Spotify, Foobar, MusicBee, etc.

**Describe alternatives you've considered**
If not an actual feature, rather an external component?

**Additional context**
Spotify Example:
![Screenshot_20220715-030911_Discord](https://user-images.githubusercontent.com/109346973/179203104-889311fb-cb3f-487c-a2da-1e05300a2728.jpg)

**Comment by MuntashirAkon** [comment]
Discord is a proprietary software, and Metro does not support proprietary software.
