### ISSUE TITLE
Subsonic Integration

### ISSUE THREAD

**Issue by coromjones97** [MuntashirAkon/Metro#119]
I love the UI and design of your app. I haven't seen anything better, you have done a remarkable job.

I use a self-hosted music server that uses the subsonic API, I love to have access to my hundreds of gigabytes of music super easy. I host because I prefer the hi-res audio. I'm not sure if it's in the plans to integrate but I would love to see it brought to the app. Let me know if this is a future plan.

Keep up the good work!!

**Comment by MuntashirAkon** [comment]
This is a offline music player.
