### ISSUE TITLE
Rotating device crashes the player while in the app

### ISSUE THREAD

**Issue by RilicTheFox** [MuntashirAkon/Metro#12]
I'm currently on Android 10 on a Samsung s10e that is running a custom rom close to stock AOSP. When I rotate the app while its open, the app crashes.
Another thing I've noticed is that the new[ seeking feature in Android 10's music player notifications](https://beebom.com/spotify-seekable-progress-bar-android-10/) doesn't work, only showing a blank bar. It looks like this has to be implemented manually, though, so it might just be a case of using the code from the latest Retro version for it.
Do you think these are possible to be solved/implemented? I saw in other issues that you don't have an Android 10 device to test with, so I'm happy to test any builds to do with these issues on my own device!
Cheers

**Comment by RilicTheFox** [comment]
Oookay, so both issues fixed themselves as I re-opened it a few times. That's... odd.
I'm gonna close this for now. Sorry.

**Comment by MuntashirAkon** [comment]
Yes, this issue should be fixed in v3.5.10 along with the playlist issue.

**Comment by RilicTheFox** [comment]
Wait, something is definitely happening. I have that version installed.
The rotational crashing seems like it's to do with what Now Playing theme you're using. As for the seek bar in the player notification, that seems hit or miss depending on how and when you open the app. No correlation there, yet.

The themes that do work have an odd behaviour: on rotation, it seems to close the Now Playing pullout and bring you back to the screen you were at before.

Theme-by-theme testing:
**Adaptive:** ✔️ 
**Blur**: ❌ 
**Blur Card**: ✔️
**Card**: ✔️
**Circle:** ✔️
**Classic:** ✔️
**Color**: ❌ 
**Fit**: ✔️ 
**Flat**: ❌ 
**Fill**: ✔️ 
**Gradient**: ✔️
**Material**: ❌ 
**Normal**: ❌ 
**Plain**: ❌ 
**Simple:**: ❌
**Tiny**: ✔️ (i am so confused by this theme)

There seems to be a correlation in the ones that crash: they all use square, seemingly untransformed album art.
Here is a crash log: https://del.dog/yrettepewa.txt

I'm re-opening the issue since I've tested and confirmed this is still a problem in v3.5.10. Sorry about that!

**Comment by MuntashirAkon** [comment]
I've made a new release. Check it again.

**Comment by RilicTheFox** [comment]
> I've made a new release. Check it again.

I can't open the app to test it after installing the new release, as it crashes on opening.
Here is the log: https://del.dog/peminepeca

Is this a new issue?

**Comment by MuntashirAkon** [comment]
> Is this a new issue?

I've updated the release. App optimisation was enabled in the upstream repo which caused the problem. I've fixed it now.

**Comment by RilicTheFox** [comment]
That did it! The original issue of the rotation crash is fixed, too. Closing this issue.
