### ISSUE TITLE
add support for more sites for synced lyrics

### ISSUE THREAD

**Issue by Relected** [MuntashirAkon/Metro#125]
**Is your feature request related to a problem? Please describe.**

a lot of songs I have don't have their synced lyrics in lyricsify, but they do exist in other sites such as kugou, netease and QQ

**Describe the solution you'd like**

adding support for downloading lyrics from these sites locally and rename them to the same filename of the song, and save them side by side on the same folder

**Describe alternatives you've considered**

APlayer has those extra sites, but it lacks other features, and it saves the synced lyrics in its own data folder with weird namings in it, it also has anti-features

**Additional context**

maybe have an option to automatically download available synced lyrics, with search priority.

**Comment by MuntashirAkon** [comment]
Metro is a fully offline player. It does not connect to the Internet i.e. it has no INTERNET permission.
