### ISSUE TITLE
Add an option in settings to re-enable Online Features

### ISSUE THREAD

**Issue by DavidRLTG** [MuntashirAkon/Metro#135]
**Is your feature request related to a problem? Please describe.**
Nono, I just miss the online features.

**Describe the solution you'd like**
I wish for a toggle in settings that re-enables online features such as fetching Artist Info. Please?

**Describe alternatives you've considered**
I don't have any :(

**Additional context**
What else should I say?!

**Comment by MuntashirAkon** [comment]
The purpose of Metro is to create a fully offline music player. Use Retro itself if you need Internet features.
