### ISSUE TITLE
Metro Crashes on Android 11

### ISSUE THREAD

**Issue by TuxKruger** [MuntashirAkon/Metro#16]
Hey dev! I have really enjoyed your app a lot on previous Android versions. Now I have recently upgraded to Android 11 and now I am facing a critical issue.

Yes I have read FAQ and other issues before making this issue.

**Description**
Metro Crashes when trying to open the app (even for the first time)

**How To Reproduce**
1.  Install the apk on Android 11
2. Try to open the app

**Screenshots**
![Screenshot_20200926-112141.png](https://user-images.githubusercontent.com/39946309/94331494-7777ee00-ffea-11ea-9e42-2b124642581c.png)

**Crash log**
I have grabbed the logs but I don't understand it so I can't really explain anything about it....
https://pastebin.com/qxYXwzFp 

**Device info:**
 - Device: Redmi Note 9S
 - Android version: R
 - App version: 3.5.10

**Comment by MuntashirAkon** [comment]
It is the scope storage problem I think as you can only use SAF in Android 11.

**Comment by TuxKruger** [comment]
I just tried the original Retro Music Player and it actually works. Metro Music is a fork of Retro Music Player so isn't it supposed to work similarly?

**Comment by MuntashirAkon** [comment]
> I just tried the original Retro Music Player and it actually works. Metro Music is a fork of Retro Music Player so isn't it supposed to work similarly?

Yes, but they don't use they same release pattern as I do (they, in fact, do not make any release on Github now).

**Comment by MuntashirAkon** [comment]
I've just made a new release. Check if it works.

**Comment by TuxKruger** [comment]
The new version works! No crashes now! Thanks dev!

**Comment by TuxKruger** [comment]
I think I should close my issue now
