### ISSUE TITLE
Include compiled apks in Github releases.

### ISSUE THREAD

**Issue by Siriusmart** [MuntashirAkon/Metro#162]
**Is your feature request related to a problem? Please describe.**
Currently the ads and crash from upstream code is removed from the repository, but the F-Droid version is still waiting for compile, therefore not available to most people.

**Describe the solution you'd like**
Include compiled apks in Github releases.

**Comment by NayamAmarshe** [comment]
+1. Please make it happen!🙌

**Comment by MuntashirAkon** [comment]
This is for F-Droid only.

**Comment by NayamAmarshe** [comment]
I have to ask 'why?' though. What's the harm in including the APKs under releases? License or something else?
