### ISSUE TITLE
App crashes in queue page

### ISSUE THREAD

**Issue by 2ndemosthenes** [MuntashirAkon/Metro#17]
**Describe the bug**
Trying to go to Album or Artist in the queue page makes the app crash.

**How To Reproduce**
1. Play a song (or a list of songs) 
2. Go to Queue page
3. Tap the 3 dot menu
4. Select "Go to artist" or "Go to album" 

**Expected behavior**
The app should go to the album/artist page

**Device info:**
Device info:
---
<table>
<tr><td><b>App version</b></td><td>3.5.11</td></tr>
<tr><td>App version code</td><td>10445</td></tr>
<tr><td>Android build version</td><td>166(C185)</td></tr>
<tr><td>Android release version</td><td>8.0.0</td></tr>
<tr><td>Android SDK version</td><td>26</td></tr>
<tr><td>Android build ID</td><td>LDN-L21 8.0.0.166(C185)</td></tr>
<tr><td>Device brand</td><td>HUAWEI</td></tr>
<tr><td>Device manufacturer</td><td>HUAWEI</td></tr>
<tr><td>Device name</td><td>HWLDN-Q</td></tr>
<tr><td>Device model</td><td>LDN-L21</td></tr>
<tr><td>Device product name</td><td>LDN-L21B</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
<tr><td>Language</td><td>auto</td></tr>
</table>

**Comment by Mk1378** [comment]
The bug still exists in the new version

**Comment by akhilamadari** [comment]
any update on this?
