### ISSUE TITLE
App crashes when trying to shuffle all by pop up on home screen

### ISSUE THREAD

**Issue by katxt** [MuntashirAkon/Metro#18]
**Screenshots**
![Screenshot_20200930-103101_Shade Launcher.jpg](https://user-images.githubusercontent.com/67353840/94640385-be2a5880-0308-11eb-8991-c70e25da3ead.jpg)

**Device info:**
 - Device: Samsung A10s
 - Android version: Android 10
 - App version 3.5.11_10445

**Comment by MuntashirAkon** [comment]
Fixed.
