### ISSUE TITLE
[Feature Request] Option to change text size for track listings inside albums

### ISSUE THREAD

**Issue by coderkei** [MuntashirAkon/Metro#21]
**Is your feature request related to a problem? Please describe.**
Problem: For some of my albums, when I view their track listings, the font size is very large so many of my songs have their names cut off. For compilations that I have numbered at the end of the song title name, it often means I have no way of knowing which one is it without playing it first. It appears to only show up to 20 characters before cutting off.

**Describe the solution you'd like**
Solution: Please can I request a feature to reduce the size of track listings inside albums. Additionally please can I request this for the main album view too as the text is large there and cuts off the album name too when I switch  to the smaller 3x3 grid option.

**Describe alternatives you've considered**
The only alternative I can try is another music player, but I like the design of this player. I know that some players such as Vanilla Music solve this by rendering the song name as two lines if required.

**Comment by MuntashirAkon** [comment]
> I know that some players such as Vanilla Music solve this by rendering the song name as two lines if required.

I'll see if I can do something like this here as well.

I think the overall font size used by Retro Music (and therefore Metro) is too large compared to other music apps such as Poweramp.

**Comment by TheEvilSkeleton** [comment]
I wouldn't mind testing this if you ever submit an MR (but I'll need guidance to compile it).

**Comment by kaikun97** [comment]
Yeah I would say as a separate issue there needs to be some build instructions. I haven't been able to find any, both for this repo and the original retro repo.

**Comment by MuntashirAkon** [comment]
You don't need any instructions. Just clone the repo, open it via **Android Studio** and let it do its job. After its done, use the build or run button to build (and run) it.
