### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by GEkuL** [MuntashirAkon/Metro#23]
The songs are visible for the player and I even can play them. Yet I can't find none of them in the search bar getting the message "No results" 

Version 4.0.010 Pro from FDroid

**Comment by MuntashirAkon** [comment]
This is a known issue. You have to input some queries to get results.

**Comment by MuntashirAkon** [comment]
And please use the issue template next time you create an issue. It's easier to manage this way.
