### ISSUE TITLE
In album view, tracks are not sorted numerical

### ISSUE THREAD

**Issue by jooooscha** [MuntashirAkon/Metro#24]
On album view, if the list is sorted by track number, a track with the tracknumber 10 is sorted directly after a song with the number 1 and before a song with the track number 2.

This bug does not exist in the artist view.

**Comment by worthlessDev** [comment]
Although this is not a solution, if you reselect "Track number" under the sort options it will organize the tracks correctly (ie. 1,2,3,...)
