### ISSUE TITLE
Update Icon on F-droid

### ISSUE THREAD

**Issue by LongJohn-Silver** [MuntashirAkon/Metro#25]
**Have you read the [FAQ](https://www.github.com/h4h13/RetroMusicPlayer/tree/dev/FAQ.md)?**
[Yes]

**Describe the bug**
The icon on the F-droid repository is still the old R icon which I assume is from Retro.

**How To Reproduce**
1.  Go to F-droid.
2. Search for Metro.
3. Find Metro with old icon.

**Expected behavior**
That the new triangular icon shows up instead of that one.

**Screenshots**
N/A.

**Crash log**
N/A.

**Device info:**
 - Device: N/A.
 - Android version: N/A.
 - App version: N/A.

**Additional context**
N/A.

**Comment by LongJohn-Silver** [comment]
This wasn't fixed event though it was closed, is there a reason?

**Comment by MuntashirAkon** [comment]
> This wasn't fixed event though it was closed, is there a reason?

The icon has been updated in the fastlane and therefore, I've closed it. I'm not sure why F-Droid didn't pick it up yet.

**Comment by LongJohn-Silver** [comment]
Oh, okay, is this being discussed on GitLab?
