### ISSUE TITLE
Impossible to add songs to Playlist [Android 10]

### ISSUE THREAD

**Issue by icypolarbear** [MuntashirAkon/Metro#3]
It's impossible to add songs to a playlist, if they are stored on an external SD card. 
This happens on Android 10. 
Whenever I try to add songs from the SD card to my playlist the song counter stays at 0.

**Comment by MuntashirAkon** [comment]
See https://github.com/h4h13/RetroMusicPlayer/issues/801#issuecomment-647130668

**Comment by icypolarbear** [comment]
Okay, thanks!
