### ISSUE TITLE
Too much permissions?

### ISSUE THREAD

**Issue by VicFic2006** [MuntashirAkon/Metro#31]
I'm not an android app expert so I maybe wrong but isn't it too much permissions for a _music player_?
Sorry if I'm wrong but as a normie browsing through Fdroid, it seemed a bit too much.
![image](https://user-images.githubusercontent.com/53941989/98080893-3520b700-1e9c-11eb-899d-f0d82b451c57.png)

**Comment by MuntashirAkon** [comment]
Metro (Retro Music) offers many features that need all these permissions. Most of them are optional and never used unless explicitly enabled in settings.

**Comment by MuntashirAkon** [comment]
#41
