### ISSUE TITLE
Like button doesn't work from the notification panel.

### ISSUE THREAD

**Issue by newmetrouser** [MuntashirAkon/Metro#32]
Describe the bug: 
Like button in the notification panel is not working, so the songs can't be added as favorite from the notification. 
(But the like button works perfectly in the Now Playing screen)

1. Play a song on Metro.
2. Swipe down the notification panel.
3. Tap on the like button to add as favorite.

Expected behavior: Tapping the like button from the notifications for a song should add  that song as a favorite.

Device info:
 -Device: Realme 7
 -Android version: Android 10
 -App version: Metro v4.0.010

**Comment by MuntashirAkon** [comment]
Fixed.

**Comment by newmetrouser** [comment]
> Fixed.

Okay so I am new to all this, how to get the fixed version ?

**Comment by MuntashirAkon** [comment]
> Okay so I am new to all this, how to get the fixed version ?

Wait for the next release.

**Comment by newmetrouser** [comment]
> Wait for the next release.

I am an absolute idiot aren't I. sorry for wasting your time lol. Anyway, could you also make the text smaller in the now playing screen (song name and artist name) 

Thanks a lot regardless.

**Comment by MuntashirAkon** [comment]
> Anyway, could you also make the text smaller in the now playing screen

Already done as part of #21. Just wait for the next release.

**Comment by newmetrouser** [comment]
> Already done as part of #21. Just wait for the next release.

Hey, Muntashir, sorry to bother you again.
I need to inform you about another thing and I am unsure if this would be an issue or a feature request.

So, usually the 'Adaptive Color' option looks stunning but sometimes when the album art is dark, the progress bar and volume control bar on the Now Playing screen is near invisible. 

It would be so much better if instead of black it was white or something else. Could you somehow make the two bars turn white automatically whenever the progress bars become near invisible?

Like in this case with Furious 7 cover, you will observe that the volume control bar is almost invisible. 

One way would be to just disable adaptive color but it would so sweet if you could somehow fix this ? 
![Screenshot_2020-11-07-17-15-31-26](https://user-images.githubusercontent.com/74034195/98440223-a1f6b400-211d-11eb-9965-e696abd4f8cd.jpg)
