### ISSUE TITLE
Stream app's library to desktop?

### ISSUE THREAD

**Issue by Oclair** [MuntashirAkon/Metro#35]
Hey I can't believe how incredible this app is, using it over the last few days I would like to be able to share the library with my desktop computer.  For example my macbook pro, Apple now sells computers with ridiculously small storage.  The ability to stream the library locally would be awesome.

Thanks for your consideration, maybe I missed the feature somewhere but I've looked quite extensively.
Have a great day,
OC

**Comment by MuntashirAkon** [comment]
Sorry. Not possible with this app as it's designed for offline and in-device music playback. Possibly sharing your library via FTP and mounting it on your Macbook Pro as an external drive is a better idea.
