### ISSUE TITLE
AntiFeature: Unable to disable AudioScrobble

### ISSUE THREAD

**Issue by ghost** [MuntashirAkon/Metro#41]
AudioScrobble can't be disabled from what I see. This would count as an AntiFeature according to F-Droid, a toggle should be added to disable it

**Comment by MuntashirAkon** [comment]
I aim to remove the Internet permission altogether as it's not really required for Metro. Related to #31. This will also make it a bit lighter.

**Comment by adarsh1001** [comment]
Currently, I can see a ton of internet activity going on in the background and I'm not entirely sure what is being sent and for what purpose. Might be related to the Scrobbler API. In any case, would be amazing to have a completely offline player.

![Screenshot_20220523-170024.png](https://user-images.githubusercontent.com/8820038/169811035-d87a6ed5-a887-4ec3-b626-08caabba7a25.png)

**Comment by MuntashirAkon** [comment]
Yes, working on it and will be removed in the next version. I intended to remove everything but I may reconsider keeping the lyrics downloader.

**Comment by MuntashirAkon** [comment]
12bded6
