### ISSUE TITLE
Rename "Hong Kong China" language option to "Hong Kong"

### ISSUE THREAD

**Issue by TheOPtimal** [MuntashirAkon/Metro#46]
Go in application settings > Other > Select Language

Liberate Hong Kong!

**Comment by gnuhead-chieb** [comment]
I sent pull request to upstream repo.
https://github.com/h4h13/RetroMusicPlayer/pull/1046
When it is merged,it will fixed soon.

**Comment by MuntashirAkon** [comment]
c1b341ad51683b485d04cd26463432defc09efbf
