### ISSUE TITLE
some buttons are unclickable

### ISSUE THREAD

**Issue by KraXen72** [MuntashirAkon/Metro#47]
when you have shuffle on, and you turn it off and on, you can't click the three dots in the bottom. or any other of the bottom buttons, until you close the big music player screen (by swiping down) and open it back up (by swiping up from miniplayer)

i tried this with the blur and normal theme. both have this bug. 

my phone is samsung galaxy m21 with android 10 and i downloaded metro from fdroid

**Comment by MuntashirAkon** [comment]
c1b341ad
