### ISSUE TITLE
Retro was discontinued.

### ISSUE THREAD

**Issue by tpurde** [MuntashirAkon/Metro#54]
RetroMusicPlayer was recently discontinued. Metro is one of the best music players I've ever used and I'd hate to see it gone. So, @MuntashirAkon, what do you plan to do for the future?

**Comment by EuriNaiz** [comment]
I was thinking in that... what will happen with Metro? Will you continue the project? The Retro's dev said if we found people to continue the proyect, we could do it c:

**Comment by metronightly** [comment]
Good news. Retro Music Player is back in development. I hope Muntashir keeps on developing Metro too.

**Comment by MuntashirAkon** [comment]
I initially decided to discontinue Metro as well (I was ignoring all the notifications from this project as a result). But I am currently content with keeping it in the maintenance mode since the upstream is active again. However, any user contributions will always be welcome.
