### ISSUE TITLE
Old version of fastscroller library

### ISSUE THREAD

**Issue by john2020star** [MuntashirAkon/Metro#55]
Hi,

I found there is a bug that can cause compatibility issues in the library me.zhanghai.fastscroller [https://github.com/zhanghai/AndroidFastScroll/issues/32], this bug has been fixed in version 1.1.5. I noticed that you stick on the library in 1.1.0, please upgrade it.

**Comment by MuntashirAkon** [comment]
c1b341ad51683b485d04cd26463432defc09efbf
