### ISSUE TITLE
keep it updated

### ISSUE THREAD

**Issue by cauerego** [MuntashirAkon/Metro#63]
once i liked retro.

and i love the robin hood idea of metro!

but, above all, is this legal?

and can you keep it updated?

perhaps, can i help? not sure how... but might work for anyone else. 😁

**Comment by 2ndemosthenes** [comment]
It's completely legal, now that Retro has restarted its development, hopefully Metro would get updated too.

**Comment by cauerego** [comment]
bleh... it still looks too unstable for me, after all.

search almost never works anymore.

can't bother to report the bug there...

just wanted to tell you that i found another interesting player. hope this will be good enough for the rest of the year: pulse.

it's not a phonograph fork, apparently.

cheers! 😘
