### ISSUE TITLE
Search button too far from 

### ISSUE THREAD

**Issue by MichalLebeda** [MuntashirAkon/Metro#65]
**Is your feature request related to a problem? Please describe.**
Search button is too far from thumb. It is rather critical to have all needed elements accessible on bigger screens.

**Describe the solution you'd like**
I think using FAB would be ideal solution. 

**Describe alternatives you've considered**
Let's discuss them, I don't have any at the moment.

**Additional context**
I can volunteer to implement this, but I want to be sure that there aren't any problems and my work would be accepted (maybe I would like to implement #52  in one PR)

**Comment by MuntashirAkon** [comment]
Go to **Settings** > **Personalize** > **Library categories** and select **Search**.
