### ISSUE TITLE
Equalizer?

### ISSUE THREAD

**Issue by HonestAbe7** [MuntashirAkon/Metro#76]
Is there a equalizer in this app because now it is grayed out in the settings? I thought there was one in the previous version?

**Comment by MuntashirAkon** [comment]
I will look into it. It's probably disabled for some reasons for the release build.

**Comment by MuntashirAkon** [comment]
Metro only supports the built-in equaliser. If it's not present, it will be greyed out. If your device has a different equaliser, you can specify the package name here.
