### ISSUE TITLE
Bug Report: Player Crashes When Rotating Screen

### ISSUE THREAD

**Issue by HonestAbe7** [MuntashirAkon/Metro#77]
Here is my bug report text. It looks like there is a crash when rotating the screen when playing a song.

[bug_report-2022-05-24.txt](https://github.com/MuntashirAkon/Metro/files/8766402/bug_report-2022-05-24.txt)

**Comment by MuntashirAkon** [comment]
5e8dba4d909047663ad800a918b7354a305c1a22
