### ISSUE TITLE
Show the images of each music when viewing the music list of an Artist/Album. 

### ISSUE THREAD

**Issue by qzvxg2e680r** [MuntashirAkon/Metro#78]
**Is your feature request related to a problem? Please describe.**
Not a problem, but an inconvenience, especially when rely on images to identify a music.
Example: Music title is in a different language

**Describe the solution you'd like**
Similar to the "Genre" tab, images of each music should be shown when viewing the music list of an artist or album.
Each music should be [Image] [Title], just like how the main "Songs" tab does it.

**Describe alternatives you've considered**
N/A

**Additional context**
Image from Retro Music Player.
It should look like this when clicking an artist/album too.
![songs](https://user-images.githubusercontent.com/106213781/170165891-d61bb299-77c5-4c86-933d-95e5ee4e5d61.jpg)

**Comment by MuntashirAkon** [comment]
36ecfb678ee1c43651e6dfed522ebeedbc73ab44
