### ISSUE TITLE
App name when installed

### ISSUE THREAD

**Issue by Beventar** [MuntashirAkon/Metro#83]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When installed make the apps name something like "Music" or "Metro Music"

**Additional context**
It looks a lot nicer in my opinion.

**Comment by yephny** [comment]
It's subjective. Metro Music and Bromite Browser both sound weird to me. You could try a launcher that allows you to rename apps, like Olauncher Clutter Free.
