### ISSUE TITLE
Album track order random in "now playing" queue

### ISSUE THREAD

**Issue by julmey** [MuntashirAkon/Metro#87]
In the album view the tracks are shown in the correct order, but as soon as I tap on "play all", the songs play randomly after the first song. Other than the actual first song being played first, there is no difference between shuffle and play all.

**Comment by soopstar** [comment]
Have you tried toggling "Shuffle mode" under "Audio" in the settings?

**Comment by julmey** [comment]
Now I feel dumb, thank you very much! Didn't really get what that setting does until now.

**Comment by soopstar** [comment]
Don't worry. I feel like that setting is a bit confusing, anyways
